#!/bin/bash
CFLAGS='-g3 -O0' CXXFLAGS='-g3 -O0' ./configure \
  --prefix=$HOME/opt/bochs-dbg \
  --enable-disasm \
  --enable-debugger \
  --disable-docbook \
  --disable-vbe \
  --disable-fpu \
  --enable-cpu-level=3 \
  --disable-cdrom \
  --enable-logging \
  --enable-instrumentation="instrument/example2"
